cache:
  directories:
    - node_modules

language: node_js
node_js:
  - "node"
  - "lts/*"
  - "8"
  - "10"

install:
  - (cd simple-promise-queue && yarn)

script:
  - (cd simple-promise-queue && yarn test)