cache:
  directories:
    - node_modules

language: node_js
node_js:
  - "6.0"
  - "7.0"
  - "8.0"
install:
  - cd ${TRAVIS_BUILD_DIR}/simple-promise-queue && npm i

script:
  - cd ${TRAVIS_BUILD_DIR}/simple-promise-queue && npm run test